Keep the track of current path for types "shouldPopUntil" and "pushNamedAndRemoveUntil".
flutterings/flutter_redux_navigation pull request #24
Opened 2021-10-06 21:05 UTC by 0rangeFox

This pull request aims to maintain the paths whenever it is moved via the methods said in the title, and to remove the previous ones.

2021-10-07 07:52 UTC, esarbanis requested changes
Please revert all changes on the imports and formatting, it is really difficult to follow what has changed. Make sure to only include changes appropriate to the PR scope.

Can you also include a couple of tests?

2021-10-07 07:52 UTC, esarbanis commented on pubspec.yaml
> +version: 0.7.1
This is done by the maintainer, please revert

2021-10-07 09:33 UTC, 0rangeFox commented
Why I should revert the imports? This way everything works properly and keeps things more organized to distinguish the differences between what is in the current package with the outside package. About formatting, I have tried my best for better understandability, I think it is very simple and understandable.

2021-10-07 09:50 UTC, esarbanis commented
@0rangeFox changing the imports is ok with me, just not in the same PR and commit where `shouldPopUntil` and `pushNamedAndRemoveUntil` are added. Please create a separate request for this change.

In this project, we use `dart format` for code formatting, so please make sure to use this approach.

Please also add a test for this change.

2021-10-07 10:03 UTC, 0rangeFox commented
Ah okay, I get it, about the tests, I haven't worked with that much, but I will try to see what I can do on it.

2021-10-07 10:16 UTC, esarbanis commented
Thanks, @0rangeFox !

2021-10-07 11:14 UTC, 0rangeFox commented on pubspec.yaml
> +version: 0.7.1
Done.

2021-10-07 11:16 UTC, 0rangeFox commented
About testing, I couldn't run it because it gave me an error with the build runner saying the following: `Could not find a file named "pubspec.yaml" in "C:\Users\0rangeFox\AppDataLocal\Pub\Cache\hosted\pub.dartlang.org\_fe_analyzer_shared-28.0.0"`, and I couldn't find anything on the internet related to this, and I think it's that code implementation.

2021-11-30 13:50 UTC, 0rangeFox commented
Hey, this has been a long time without receiving an answer, could you tell me something about this?

2022-05-11 21:10 UTC, closed without merging