Add alias so NavigationDestination does not break
flutterings/flutter_redux_navigation pull request #26
Opened 2021-12-09 13:21 UTC by leonardo2204

2021-12-09 13:28 UTC, leonardo2204 commented
@esarbanis See if it's ok, please.

2021-12-27 20:25 UTC, esarbanis requested changes
Thanks for this @leonardo2204 !

Can you please instead of using the`NavDestination` alias, replace the 1st import with:
`package:flutter/widgets.dart`

2021-12-28 14:39 UTC, leonardo2204 commented
@esarbanis Thank you, just did it!

2021-12-28 14:56 UTC, esarbanis requested changes
Can you also squash your commits into one :sweat_smile:

2021-12-28 15:17 UTC, leonardo2204 commented
Done, @esarbanis!

2021-12-28 15:29 UTC, merged

2021-12-28 15:29 UTC, esarbanis approved these changes